# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'basic_control.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1183, 640)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_Reset = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Reset.setGeometry(QtCore.QRect(240, 20, 90, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_Reset.setFont(font)
        self.pushButton_Reset.setObjectName("pushButton_Reset")
        self.pushButton_ModeSet = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ModeSet.setGeometry(QtCore.QRect(390, 20, 90, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_ModeSet.setFont(font)
        self.pushButton_ModeSet.setObjectName("pushButton_ModeSet")
        self.pushButton_OnlineCheck = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_OnlineCheck.setGeometry(QtCore.QRect(540, 20, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_OnlineCheck.setFont(font)
        self.pushButton_OnlineCheck.setObjectName("pushButton_OnlineCheck")
        self.pushButton_Feedback = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Feedback.setGeometry(QtCore.QRect(700, 20, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_Feedback.setFont(font)
        self.pushButton_Feedback.setObjectName("pushButton_Feedback")
        self.pushButton_Stop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Stop.setGeometry(QtCore.QRect(860, 20, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_Stop.setFont(font)
        self.pushButton_Stop.setObjectName("pushButton_Stop")
        self.label_Coil1 = QtWidgets.QLabel(self.centralwidget)
        self.label_Coil1.setGeometry(QtCore.QRect(20, 130, 51, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_Coil1.setFont(font)
        self.label_Coil1.setObjectName("label_Coil1")
        self.Dial_Value1 = QwtDial(self.centralwidget)
        self.Dial_Value1.setGeometry(QtCore.QRect(60, 160, 151, 141))
        self.Dial_Value1.setLineWidth(4)
        self.Dial_Value1.setObjectName("Dial_Value1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 130, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_Value1 = QtWidgets.QLabel(self.centralwidget)
        self.label_Value1.setGeometry(QtCore.QRect(70, 300, 67, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_Value1.setFont(font)
        self.label_Value1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Value1.setObjectName("label_Value1")
        self.pushButton_Set1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Set1.setGeometry(QtCore.QRect(170, 130, 51, 21))
        self.pushButton_Set1.setObjectName("pushButton_Set1")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 110, 1151, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(140, 300, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_Coil2 = QtWidgets.QLabel(self.centralwidget)
        self.label_Coil2.setGeometry(QtCore.QRect(250, 130, 51, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_Coil2.setFont(font)
        self.label_Coil2.setObjectName("label_Coil2")
        self.pushButton_Set2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Set2.setGeometry(QtCore.QRect(400, 130, 51, 21))
        self.pushButton_Set2.setObjectName("pushButton_Set2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(360, 130, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.Dial_Value2 = QwtDial(self.centralwidget)
        self.Dial_Value2.setGeometry(QtCore.QRect(290, 160, 151, 141))
        self.Dial_Value2.setLineWidth(4)
        self.Dial_Value2.setObjectName("Dial_Value2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(370, 300, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_Value2 = QtWidgets.QLabel(self.centralwidget)
        self.label_Value2.setGeometry(QtCore.QRect(300, 300, 67, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_Value2.setFont(font)
        self.label_Value2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Value2.setObjectName("label_Value2")
        self.label_Coil3 = QtWidgets.QLabel(self.centralwidget)
        self.label_Coil3.setGeometry(QtCore.QRect(480, 130, 51, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_Coil3.setFont(font)
        self.label_Coil3.setObjectName("label_Coil3")
        self.pushButton_Set3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Set3.setGeometry(QtCore.QRect(630, 130, 51, 21))
        self.pushButton_Set3.setObjectName("pushButton_Set3")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(590, 130, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.Dial_Value3 = QwtDial(self.centralwidget)
        self.Dial_Value3.setGeometry(QtCore.QRect(520, 160, 151, 141))
        self.Dial_Value3.setLineWidth(4)
        self.Dial_Value3.setObjectName("Dial_Value3")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(600, 300, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_Value3 = QtWidgets.QLabel(self.centralwidget)
        self.label_Value3.setGeometry(QtCore.QRect(530, 300, 67, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_Value3.setFont(font)
        self.label_Value3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Value3.setObjectName("label_Value3")
        self.label_Coil4 = QtWidgets.QLabel(self.centralwidget)
        self.label_Coil4.setGeometry(QtCore.QRect(710, 130, 51, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_Coil4.setFont(font)
        self.label_Coil4.setObjectName("label_Coil4")
        self.pushButton_Set4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Set4.setGeometry(QtCore.QRect(860, 130, 51, 21))
        self.pushButton_Set4.setObjectName("pushButton_Set4")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(820, 130, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.Dial_Value4 = QwtDial(self.centralwidget)
        self.Dial_Value4.setGeometry(QtCore.QRect(750, 160, 151, 141))
        self.Dial_Value4.setLineWidth(4)
        self.Dial_Value4.setObjectName("Dial_Value4")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(830, 300, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_Value4 = QtWidgets.QLabel(self.centralwidget)
        self.label_Value4.setGeometry(QtCore.QRect(760, 300, 67, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_Value4.setFont(font)
        self.label_Value4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Value4.setObjectName("label_Value4")
        self.label_Coil5 = QtWidgets.QLabel(self.centralwidget)
        self.label_Coil5.setGeometry(QtCore.QRect(940, 130, 51, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_Coil5.setFont(font)
        self.label_Coil5.setObjectName("label_Coil5")
        self.pushButton_Set5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Set5.setGeometry(QtCore.QRect(1090, 130, 51, 21))
        self.pushButton_Set5.setObjectName("pushButton_Set5")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(1050, 130, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.Dial_Value5 = QwtDial(self.centralwidget)
        self.Dial_Value5.setGeometry(QtCore.QRect(980, 160, 151, 141))
        self.Dial_Value5.setLineWidth(4)
        self.Dial_Value5.setObjectName("Dial_Value5")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(1060, 300, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_Value5 = QtWidgets.QLabel(self.centralwidget)
        self.label_Value5.setGeometry(QtCore.QRect(990, 300, 67, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_Value5.setFont(font)
        self.label_Value5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Value5.setObjectName("label_Value5")
        self.pushButton_Set6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Set6.setGeometry(QtCore.QRect(170, 340, 51, 21))
        self.pushButton_Set6.setObjectName("pushButton_Set6")
        self.Dial_Value7 = QwtDial(self.centralwidget)
        self.Dial_Value7.setGeometry(QtCore.QRect(290, 370, 151, 141))
        self.Dial_Value7.setLineWidth(4)
        self.Dial_Value7.setObjectName("Dial_Value7")
        self.label_Value6 = QtWidgets.QLabel(self.centralwidget)
        self.label_Value6.setGeometry(QtCore.QRect(70, 510, 67, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_Value6.setFont(font)
        self.label_Value6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Value6.setObjectName("label_Value6")
        self.pushButton_Set8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Set8.setGeometry(QtCore.QRect(630, 340, 51, 21))
        self.pushButton_Set8.setObjectName("pushButton_Set8")
        self.Dial_Value9 = QwtDial(self.centralwidget)
        self.Dial_Value9.setGeometry(QtCore.QRect(750, 370, 151, 141))
        self.Dial_Value9.setLineWidth(4)
        self.Dial_Value9.setObjectName("Dial_Value9")
        self.pushButton_Set7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Set7.setGeometry(QtCore.QRect(400, 340, 51, 21))
        self.pushButton_Set7.setObjectName("pushButton_Set7")
        self.label_Coil10 = QtWidgets.QLabel(self.centralwidget)
        self.label_Coil10.setGeometry(QtCore.QRect(930, 340, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_Coil10.setFont(font)
        self.label_Coil10.setObjectName("label_Coil10")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(130, 340, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.Dial_Value10 = QwtDial(self.centralwidget)
        self.Dial_Value10.setGeometry(QtCore.QRect(980, 370, 151, 141))
        self.Dial_Value10.setLineWidth(4)
        self.Dial_Value10.setObjectName("Dial_Value10")
        self.Dial_Value8 = QwtDial(self.centralwidget)
        self.Dial_Value8.setGeometry(QtCore.QRect(520, 370, 151, 141))
        self.Dial_Value8.setLineWidth(4)
        self.Dial_Value8.setObjectName("Dial_Value8")
        self.label_Coil9 = QtWidgets.QLabel(self.centralwidget)
        self.label_Coil9.setGeometry(QtCore.QRect(710, 340, 51, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_Coil9.setFont(font)
        self.label_Coil9.setObjectName("label_Coil9")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(830, 510, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_Value7 = QtWidgets.QLabel(self.centralwidget)
        self.label_Value7.setGeometry(QtCore.QRect(300, 510, 67, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_Value7.setFont(font)
        self.label_Value7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Value7.setObjectName("label_Value7")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(1060, 510, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_Coil7 = QtWidgets.QLabel(self.centralwidget)
        self.label_Coil7.setGeometry(QtCore.QRect(250, 340, 51, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_Coil7.setFont(font)
        self.label_Coil7.setObjectName("label_Coil7")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(370, 510, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(140, 510, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_Coil8 = QtWidgets.QLabel(self.centralwidget)
        self.label_Coil8.setGeometry(QtCore.QRect(480, 340, 51, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_Coil8.setFont(font)
        self.label_Coil8.setObjectName("label_Coil8")
        self.pushButton_Set10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Set10.setGeometry(QtCore.QRect(1090, 340, 51, 21))
        self.pushButton_Set10.setObjectName("pushButton_Set10")
        self.pushButton_Set9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Set9.setGeometry(QtCore.QRect(860, 340, 51, 21))
        self.pushButton_Set9.setObjectName("pushButton_Set9")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(360, 340, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(1050, 340, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_Coil6 = QtWidgets.QLabel(self.centralwidget)
        self.label_Coil6.setGeometry(QtCore.QRect(20, 340, 51, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_Coil6.setFont(font)
        self.label_Coil6.setObjectName("label_Coil6")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(590, 340, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(600, 510, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.label_Value9 = QtWidgets.QLabel(self.centralwidget)
        self.label_Value9.setGeometry(QtCore.QRect(760, 510, 67, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_Value9.setFont(font)
        self.label_Value9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Value9.setObjectName("label_Value9")
        self.Dial_Value6 = QwtDial(self.centralwidget)
        self.Dial_Value6.setGeometry(QtCore.QRect(60, 370, 151, 141))
        self.Dial_Value6.setLineWidth(4)
        self.Dial_Value6.setObjectName("Dial_Value6")
        self.label_Value8 = QtWidgets.QLabel(self.centralwidget)
        self.label_Value8.setGeometry(QtCore.QRect(530, 510, 67, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_Value8.setFont(font)
        self.label_Value8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Value8.setObjectName("label_Value8")
        self.label_Value10 = QtWidgets.QLabel(self.centralwidget)
        self.label_Value10.setGeometry(QtCore.QRect(990, 510, 67, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_Value10.setFont(font)
        self.label_Value10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Value10.setObjectName("label_Value10")
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(820, 340, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(170, 570, 131, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.Thermo = QwtThermo(self.centralwidget)
        self.Thermo.setGeometry(QtCore.QRect(290, 530, 741, 60))
        self.Thermo.setUpperBound(8000.0)
        self.Thermo.setScaleMaxMajor(10)
        self.Thermo.setOrientation(QtCore.Qt.Horizontal)
        self.Thermo.setObjectName("Thermo")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 320, 1151, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_42 = QtWidgets.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(335, 70, 201, 41))
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setWordWrap(True)
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(670, 75, 161, 21))
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setWordWrap(True)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(850, 75, 191, 21))
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setWordWrap(True)
        self.label_44.setObjectName("label_44")
        self.lineEdit_Value1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Value1.setGeometry(QtCore.QRect(70, 130, 61, 21))
        self.lineEdit_Value1.setInputMask("")
        self.lineEdit_Value1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_Value1.setObjectName("lineEdit_Value1")
        self.lineEdit_Value2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Value2.setGeometry(QtCore.QRect(300, 130, 61, 21))
        self.lineEdit_Value2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_Value2.setObjectName("lineEdit_Value2")
        self.lineEdit_Value3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Value3.setGeometry(QtCore.QRect(530, 130, 61, 21))
        self.lineEdit_Value3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_Value3.setObjectName("lineEdit_Value3")
        self.lineEdit_Value4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Value4.setGeometry(QtCore.QRect(760, 130, 61, 21))
        self.lineEdit_Value4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_Value4.setObjectName("lineEdit_Value4")
        self.lineEdit_Value5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Value5.setGeometry(QtCore.QRect(990, 130, 61, 21))
        self.lineEdit_Value5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_Value5.setObjectName("lineEdit_Value5")
        self.lineEdit_Value6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Value6.setGeometry(QtCore.QRect(70, 340, 61, 21))
        self.lineEdit_Value6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_Value6.setObjectName("lineEdit_Value6")
        self.lineEdit_Value7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Value7.setGeometry(QtCore.QRect(300, 340, 61, 21))
        self.lineEdit_Value7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_Value7.setObjectName("lineEdit_Value7")
        self.lineEdit_Value8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Value8.setGeometry(QtCore.QRect(530, 340, 61, 21))
        self.lineEdit_Value8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_Value8.setObjectName("lineEdit_Value8")
        self.lineEdit_Value9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Value9.setGeometry(QtCore.QRect(760, 340, 61, 21))
        self.lineEdit_Value9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_Value9.setObjectName("lineEdit_Value9")
        self.lineEdit_Value10 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Value10.setGeometry(QtCore.QRect(990, 340, 61, 21))
        self.lineEdit_Value10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_Value10.setObjectName("lineEdit_Value10")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1183, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Basic 10 Coil Current Control"))
        self.pushButton_Reset.setText(_translate("MainWindow", "Reset"))
        self.pushButton_ModeSet.setText(_translate("MainWindow", "Mode Set"))
        self.pushButton_OnlineCheck.setText(_translate("MainWindow", "Online Check"))
        self.pushButton_Feedback.setText(_translate("MainWindow", "Feedback Set"))
        self.pushButton_Stop.setText(_translate("MainWindow", "Stop"))
        self.label_Coil1.setText(_translate("MainWindow", "Coil 1:"))
        self.label_2.setText(_translate("MainWindow", "mA"))
        self.label_Value1.setText(_translate("MainWindow", "0"))
        self.pushButton_Set1.setText(_translate("MainWindow", "Set"))
        self.label_4.setText(_translate("MainWindow", "mA"))
        self.label_Coil2.setText(_translate("MainWindow", "Coil 2:"))
        self.pushButton_Set2.setText(_translate("MainWindow", "Set"))
        self.label_6.setText(_translate("MainWindow", "mA"))
        self.label_7.setText(_translate("MainWindow", "mA"))
        self.label_Value2.setText(_translate("MainWindow", "0"))
        self.label_Coil3.setText(_translate("MainWindow", "Coil 3:"))
        self.pushButton_Set3.setText(_translate("MainWindow", "Set"))
        self.label_10.setText(_translate("MainWindow", "mA"))
        self.label_11.setText(_translate("MainWindow", "mA"))
        self.label_Value3.setText(_translate("MainWindow", "0"))
        self.label_Coil4.setText(_translate("MainWindow", "Coil 4:"))
        self.pushButton_Set4.setText(_translate("MainWindow", "Set"))
        self.label_14.setText(_translate("MainWindow", "mA"))
        self.label_15.setText(_translate("MainWindow", "mA"))
        self.label_Value4.setText(_translate("MainWindow", "0"))
        self.label_Coil5.setText(_translate("MainWindow", "Coil 5:"))
        self.pushButton_Set5.setText(_translate("MainWindow", "Set"))
        self.label_18.setText(_translate("MainWindow", "mA"))
        self.label_19.setText(_translate("MainWindow", "mA"))
        self.label_Value5.setText(_translate("MainWindow", "0"))
        self.pushButton_Set6.setText(_translate("MainWindow", "Set"))
        self.label_Value6.setText(_translate("MainWindow", "0"))
        self.pushButton_Set8.setText(_translate("MainWindow", "Set"))
        self.pushButton_Set7.setText(_translate("MainWindow", "Set"))
        self.label_Coil10.setText(_translate("MainWindow", "Coil 10:"))
        self.label_23.setText(_translate("MainWindow", "mA"))
        self.label_Coil9.setText(_translate("MainWindow", "Coil 9:"))
        self.label_25.setText(_translate("MainWindow", "mA"))
        self.label_Value7.setText(_translate("MainWindow", "0"))
        self.label_27.setText(_translate("MainWindow", "mA"))
        self.label_Coil7.setText(_translate("MainWindow", "Coil 7:"))
        self.label_29.setText(_translate("MainWindow", "mA"))
        self.label_30.setText(_translate("MainWindow", "mA"))
        self.label_Coil8.setText(_translate("MainWindow", "Coil 8:"))
        self.pushButton_Set10.setText(_translate("MainWindow", "Set"))
        self.pushButton_Set9.setText(_translate("MainWindow", "Set"))
        self.label_32.setText(_translate("MainWindow", "mA"))
        self.label_33.setText(_translate("MainWindow", "mA"))
        self.label_Coil6.setText(_translate("MainWindow", "Coil 6:"))
        self.label_35.setText(_translate("MainWindow", "mA"))
        self.label_36.setText(_translate("MainWindow", "mA"))
        self.label_Value9.setText(_translate("MainWindow", "0"))
        self.label_Value8.setText(_translate("MainWindow", "0"))
        self.label_Value10.setText(_translate("MainWindow", "0"))
        self.label_40.setText(_translate("MainWindow", "mA"))
        self.label_41.setText(_translate("MainWindow", "Total power (W):"))
        self.label_42.setText(_translate("MainWindow", "*All mode set as 2-current mode & current value as 0A"))
        self.label_43.setText(_translate("MainWindow", "*Set feedback speed"))
        self.label_44.setText(_translate("MainWindow", "*Set all current value as 0A"))
from PyQt5.Qwt import QwtDial
from PyQt5.Qwt import QwtThermo


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
